# Generated by Django 3.2.3 on 2021-07-05 11:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="time_stamp",
        ),
        migrations.AddField(
            model_name="message",
            name="unix_time_stamp",
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["sender_email", "recipient_email", "unix_time_stamp"],
                name="message_index",
            ),
        ),
    ]
