# Generated by Django 3.2.3 on 2021-07-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210705_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.EmailField(max_length=254)),
                ('second', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('image_name', models.CharField(max_length=10, unique=True)),
                ('about', models.TextField(max_length=300)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='message_index',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='unix_time_stamp',
            new_name='time_stamp',
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender_email', 'recipient_email', 'time_stamp'], name='message_index'),
        ),
    ]
