# Generated by Django 3.2.3 on 2021-07-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210707_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
