# Generated by Django 3.2.3 on 2021-07-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_message_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='message_index',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='recipient_email',
            new_name='recipient',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sender_email',
            new_name='sender',
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'recipient', 'time_stamp'], name='message_index'),
        ),
    ]
