# Generated by Django 3.2.3 on 2021-07-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210707_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connections',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
