# Generated by Django 3.2.3 on 2021-07-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_connections_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserData",
        ),
        migrations.AddField(
            model_name="user",
            name="about",
            field=models.TextField(default="Something about you :D", max_length=300),
        ),
        migrations.AddField(
            model_name="user",
            name="image_name",
            field=models.CharField(default="default.png", max_length=15),
        ),
    ]
