# Generated by Django 3.2.3 on 2021-07-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_user_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_name',
            field=models.CharField(default='default.png', max_length=15),
        ),
    ]
