# Generated by Django 3.2.3 on 2021-07-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_user_image_name'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='message_index',
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'recipient', '-time_stamp'], name='message_index'),
        ),
    ]
