# Generated by Django 3.2.3 on 2021-07-11 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210709_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image_name',
        ),
    ]
